### ISSUE TITLE
incorrect package retraction

### ISSUE THREAD

**Issue by goto1134** [exoscale/egoscale#586]
The issue is inspired by a bug report to GoLand: https://youtrack.jetbrains.com/issue/GO-15168

* clone  https://github.com/goto1134/go-retracted-version-update-bug
* run `go list -m -u -json all`

You will see the following output:
```jsonl
...
{
	"Path": "github.com/exoscale/egoscale",
	"Version": "v0.100.1",
	"Update": {
		"Path": "github.com/exoscale/egoscale",
		"Version": "v1.19.0"
	},
	"GoVersion": "1.17"
}
...
```

Instead I expected:
```jsonl
...
{
	"Path": "github.com/exoscale/egoscale",
	"Version": "v0.100.1",
	"Update": {
		"Path": "github.com/exoscale/egoscale",
		"Version": "v0.100.2"
	},
	"GoVersion": "1.17"
}
...
```

## The issue
As the documentation states,

> To retract a version, a module author should add a retract directive to go.mod, then publish a new version containing that directive. **The new version must be higher than other release or pre-release versions**; that is, the `@latest` [version query](https://go.dev/ref/mod#version-queries) should resolve to the new version before retractions are considered.
https://go.dev/ref/mod#go-mod-file-retract

The current latest version of the module (`v1.19.0`) does not have a retract directive. Please release the higher version of the module (`v1.19.1`) containing two retraction directives:
```go.mod
retract (
	v1.19.0 // Published accidentally.
	v1.19.1 // Retracts the previous version
)
```

P.S. In case of any further retractions, you will have to release a higher version of the module (e.g. `v1.19.2` and so on). Therefore, I suggest releasing a stable module version higher than v1.19.0 and continue the development from that version on.

**Comment by sauterp** [comment]
Thank you for the detailed report and the suggestion and for making the repo. I tried to reproduce the issue and to me the issue seems resolved by the retract directive we currently have:
```shell
$ go mod init example.com/foo
$ go get github.com/exoscale/egoscale@v0.100.1
go list -m -u -json all
...
{
	"Path": "github.com/exoscale/egoscale",
	"Version": "v0.100.1",
	"Time": "2023-04-26T09:05:59Z",
	"Update": {
		"Path": "github.com/exoscale/egoscale",
		"Version": "v0.102.3",
		"Time": "2024-01-15T15:22:50Z"
	},
	"Indirect": true,
	"GoVersion": "1.17"
}
...
```
So the retracted version doesn't show up in the Update to v0.100.1 anymore. Same for the repo you shared.

**Comment by ldez** [comment]
@sauterp The issue is not resolved.
You should add:
```
retract (
	v1.19.0 // Published accidentally.
	v1.19.1 // Retracts the previous version
)
```

and create a tag `v1.19.1`

https://go.dev/ref/mod#go-mod-file-retract

**Comment by sauterp** [comment]
Thank you @ldez for the details, your PR is merged and appreciated. I also created the tag.
What I still don't understand, is why the issue only reproduces in docker and why it's only visible on go.dev.

Anyway, I'll close this issue once the cache and go.dev are updated.

**Comment by ldez** [comment]
The goproxy is updated :tada: 

https://pkg.go.dev/github.com/exoscale/egoscale?tab=versions

![Screenshot 2024-04-24 at 17-50-13 egoscale package - github com_exoscale_egoscale - Go Packages](https://github.com/exoscale/egoscale/assets/5674651/8f878744-b4a9-42c9-a56d-2f63c8fb4bb4)

**Comment by sauterp** [comment]
I edited `v0.102.3` to be the latest version now. This should be all fixed not thanks to the help of @goto1134 @ldez !

I checked
```shell
go env GOPROXY
https://proxy.golang.org,direct
```
before trying to reproduce it locally, so I'm still wondering why it didn't work for me... But that's just my curiosity. This is done.
